# This is a basic workflow to help you get started with Actions

name: "Set Issue Label and Assignee"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          title-or-body: "both"
          parameters: '[ {"keywords": ["bug", "error", "wrong", "invalid", "incorrect"], "labels": ["BUG"], {"keywords": ["detail", "detailed", "information", "enhance", "help", "helpful", "improvement", "improve", "additional", "clarification"], "labels": ["needs more detail"]}, {"keywords": ["example", "sample", "code"], "labels": ["sample code"]}, {"keywords": ["reference", "method", "property", "trigger", "attribute", "analyzer"], "labels": ["reference docs"]}, {"keywords": ["REST", "API"], "labels": ["api"]}, {"keywords": ["REST", "API"], "labels": ["api"]}, {"keywords": ["NAV"], "labels": ["NAV"]}, {"keywords": ["powershell"], "labels": ["powershell"]}, {"keywords": ["report, reporting"], "labels": ["reporting"]}, {"keywords": ["web services"], "labels": ["web services"]} ]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
